name: Android CI

# This workflow runs on pushes to the 'main' branch and on any pull request.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest # Use a standard Linux runner provided by GitHub

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up the Java environment (JDK) needed to build Android apps
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'

      # Step 3: Make the Gradle wrapper executable
      # This is necessary for the Linux environment to be able to run Gradle commands.
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Step 4: Run the unit tests using the Gradle command
      # This command specifically runs the tests for the 'debug' build variant.
      - name: Run unit tests
        run: ./gradlew testDebugUnitTest